### ISSUE TITLE
运行代码后无输出，查看网页，也没有新的聊天产生

### ISSUE THREAD

**Issue by babylon2k2002** [ultrasev/chatrapper#1]
运行代码后无输出，查看网页，也没有新的聊天产生。

**Comment by ultrasev** [comment]
@babylon2k2002 在代码里 stream 函数里添加一下 `print(chunk)` 看看打出来的是什么，可能的原因：
1. token 无效或者账号被风控了
2. gpt 套了 cloudflare，需要进一步验证，这几天刚发现的。 
<img width="1226" alt="image" src="https://github.com/ultrasev/chatrapper/assets/51262739/1ce56deb-aca3-437b-b1b8-aaa3953323c5">

**Comment by Huang-WeiFu** [comment]
同样的问题，debug下去找到是403。
print(chunk)后主要内容显示是"Please try again later. If you are using a VPN, try turning it off."
访问chatgpt也确实是有在使用VPN。
那这样是cloudflare还是账号风控了？
如果是cloudflare的话，那有再更新的想法吗？
忘记说的一点是在网页端登录的情况下可以正常使用

**Comment by ultrasev** [comment]
> 同样的问题，debug下去找到是403。
> print(chunk)后主要内容显示是"Please try again later. If you are using a VPN, try turning it off."
> 访问chatgpt也确实是有在使用VPN。
> 那这样是cloudflare还是账号风控了？
> 如果是cloudflare的话，那有再更新的想法吗？
> 忘记说的一点是在网页端登录的情况下可以正常使用

@Huang-WeiFu  这种情况，我这两天也遇到了，套了cf有点麻烦，我再尝试一下其他方法，看看能不能绕过去。 

代码里面的思路，我用了很久都没有问题，刚好这两天分享出来就被风控，可真巧😂

**Comment by Huang-WeiFu** [comment]
感谢，star&fork了，期待后续更新解决

**Comment by 1487879421888** [comment]
敢问，作者，token是不是sess呢？我有几万个账号，sess已经提取，我想做一个池子，网页模拟api，进行轮询。

**Comment by ultrasev** [comment]
> 敢问，作者，token是不是sess呢？我有几万个账号，sess已经提取，我想做一个池子，网页模拟api，进行轮询。

@1487879421888  我示例里面的token就是 session 里的 accessToken，如果这个accessToken有的话，是可以模拟的。 

但这两天遇到了一个问题，OpenAI 套了 cf，如上所述，暂时没有特别好的解决办法。

**Comment by allencase** [comment]
出現 asyncio.run() cannot be called from a running even

**Comment by dngg6688** [comment]
一樣出現 asyncio.run() cannot be called from a running even

**Comment by ultrasev** [comment]
> 一樣出現 asyncio.run() cannot be called from a running even

代码是什么样的？asyncio.run 要在主线程里运行。

**Comment by Tanyangkai** [comment]
```
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```
